# Generated by Django 3.2.4 on 2021-06-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
