# Generated by Django 3.2.3 on 2021-05-29 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.CharField(max_length=300)),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('max_mark', models.IntegerField(default=0)),
                ('passing_marks', models.IntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='Test',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='students.test'),
        ),
    ]
