# Generated by Django 3.2.3 on 2021-06-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.TimeField(default='01:00:00'),
        ),
    ]
