# Generated by Django 3.2.4 on 2021-06-20 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='my_class_teacher',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_class_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
