# Generated by Django 3.2.4 on 2021-06-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_teacher_my_class_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='my_class_teacher',
        ),
    ]
