# Generated by Django 3.2.3 on 2021-06-05 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0002_test_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='max_question',
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(related_name='subject_teachers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='total_question',
            field=models.IntegerField(default=0, help_text='Total Questions You Created'),
        ),
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.TimeField(default='01:00:00', help_text='Please use the following format: <em>HH-MM-SS</em>.'),
        ),
        migrations.AlterField(
            model_name='test',
            name='make_active',
            field=models.BooleanField(default=False, help_text='Make Exam Active Please Be aware of it!!'),
        ),
        migrations.AlterField(
            model_name='test',
            name='max_mark',
            field=models.IntegerField(default=0, help_text='Max marks of this Test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='passing_marks',
            field=models.IntegerField(default=0, help_text='Keep Zero for <b>No Passing Criteria </b> and Less than <b>Max</b> marks'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_title',
            field=models.CharField(help_text='Title For Your test <b>Not Subject Name</b>', max_length=300),
        ),
    ]
