# Generated by Django 3.2.4 on 2021-06-08 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='teacher',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.teacher'),
        ),
        migrations.AlterField(
            model_name='test',
            name='teacher',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.teacher'),
        ),
    ]
