# Generated by Django 3.2.3 on 2021-05-29 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210529_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='duration',
        ),
        migrations.AddField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 14, 6, 32, 861394)),
            preserve_default=False,
        ),
    ]
