# Generated by Django 3.2.3 on 2021-05-31 18:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0002_auto_20210531_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionlist',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 23, 31, 45, 535983)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userquestionlist',
            name='student',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userquestionlist',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.test'),
        ),
    ]
