# Generated by Django 3.2.3 on 2021-06-05 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_auto_20210605_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_title',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(help_text='Enter Subject Name <b>Do Not Duplicate </b>', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(help_text='Use <b>control + arrow</b> click to select multiple teachers', related_name='subject_teachers', to=settings.AUTH_USER_MODEL, verbose_name='Select Teachers Want To Include'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_title',
            field=models.CharField(help_text='Title For Your test <b>Not Subject Name</b>', max_length=300, unique=True),
        ),
    ]
