# Generated by Django 3.2.3 on 2021-05-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20210531_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='student_option',
            field=models.CharField(blank=True, choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3'), ('4', 'Option 4')], default='', max_length=1, null=True, verbose_name="Student's Option"),
        ),
    ]
