# Generated by Django 3.2.3 on 2021-05-29 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20210529_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.test'),
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_option', models.CharField(blank=True, choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3'), ('4', 'Option 4')], max_length=1, null=True, verbose_name='Correct Option')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.question')),
            ],
        ),
    ]
