# Generated by Django 3.2.3 on 2021-06-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_studentanswer_student_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionlist',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
