# Generated by Django 3.2.3 on 2021-05-29 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210529_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.test'),
        ),
    ]
