# Generated by Django 3.2.3 on 2021-06-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_subject_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_title',
            field=models.CharField(help_text='Title For Your test <b>Not Subject Name</b>', max_length=300),
        ),
    ]
