# Generated by Django 3.2.3 on 2021-05-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentanswer_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='correct_option',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='option',
            field=models.CharField(blank=True, choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3'), ('4', 'Option 4')], max_length=1, null=True, verbose_name="Student's Option"),
        ),
    ]
