# Generated by Django 3.2.3 on 2021-06-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_userquestionlist_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='max_question',
            field=models.IntegerField(default=0),
        ),
    ]
