# Generated by Django 3.2.4 on 2021-06-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20210608_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
