# Generated by Django 3.2.3 on 2021-05-29 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20210529_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Test',
            new_name='test',
        ),
    ]
