# Generated by Django 3.2.3 on 2021-06-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_test_test_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3'), ('4', 'Option 4')], default=None, max_length=1, verbose_name='Correct Option'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_1',
            field=models.CharField(help_text='Option 1 should not to be repeat', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_2',
            field=models.CharField(help_text='Option 2 should not to be repeat', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_3',
            field=models.CharField(help_text='Option 3 should not to be repeat', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_4',
            field=models.CharField(help_text='Option 4 should not to be repeat', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_marks',
            field=models.FloatField(default=1, help_text='Marks for this question <b>Default is 1.0</b>'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_title',
            field=models.CharField(help_text='make sure question should me <b>Clear and Not Duplicate</b>', max_length=300, unique=True),
        ),
    ]
