# Generated by Django 3.2.3 on 2021-06-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_test_max_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_marks',
            field=models.FloatField(default=1),
        ),
    ]
