# Generated by Django 3.2.4 on 2021-06-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_college_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college_rollno',
            field=models.CharField(error_messages={'unique': 'This rollno has already been registered.'}, max_length=10, unique=True),
        ),
    ]
