# Generated by Django 3.2.3 on 2021-05-29 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_rename_test_question_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentanswer',
            old_name='option',
            new_name='correct_option',
        ),
    ]
