# Generated by Django 3.2.4 on 2021-06-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_college_rollno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_marks',
        ),
    ]
