# Generated by Django 3.2.4 on 2021-06-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_test_show_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionlist',
            name='login_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='test',
            name='exam_end_time',
            field=models.DateTimeField(help_text=' <em> YYYY-MM-DD HH-MM-SS (in 24hrs)</em>.'),
        ),
        migrations.AlterField(
            model_name='test',
            name='exam_start_time',
            field=models.DateTimeField(help_text=' <em> YYYY-MM-DD HH-MM-SS (in 24hrs)</em>.'),
        ),
    ]
