# Generated by Django 3.2.4 on 2021-06-26 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20210625_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquestionlist',
            old_name='end_time',
            new_name='submit_time',
        ),
    ]
