# Generated by Django 3.2.4 on 2021-06-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_rename_end_time_userquestionlist_submit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionlist',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
