# Generated by Django 3.2.4 on 2021-07-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_userquestionlist_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college_rollno',
            field=models.CharField(error_messages={'unique': 'This rollno has already been registered.'}, help_text='Only <b>Number </b>', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='userquestionlist',
            name='submit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
