# Generated by Django 3.2.5 on 2021-07-09 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_auto_20210701_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='max_mark',
        ),
    ]
