# Generated by Django 3.2.5 on 2021-07-09 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_remove_test_max_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='show_result',
            field=models.BooleanField(default=False, help_text='If you clicked from now student can  seee there result from ther dashboard '),
        ),
        migrations.AlterField(
            model_name='test',
            name='total_question',
            field=models.IntegerField(default=0, help_text='Total You want to student Answers<brq>'),
        ),
        migrations.CreateModel(
            name='ReportStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=300, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.test')),
            ],
        ),
    ]
