# Generated by Django 3.2.5 on 2021-07-09 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_auto_20210709_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportstudent',
            name='teacher',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_report', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportstudent',
            name='student',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_report', to=settings.AUTH_USER_MODEL),
        ),
    ]
